<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-25T07:47:11 IST" name="Suite" finished-at="2024-03-25T07:48:00 IST" duration-ms="48544">
    <groups>
    </groups>
    <test started-at="2024-03-25T07:47:11 IST" name="Test" finished-at="2024-03-25T07:48:00 IST" duration-ms="48544">
      <class name="TestScripts.ProductSelect">
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.ProductSelect@4470fbd6]" started-at="2024-03-25T07:47:44 IST" name="login" finished-at="2024-03-25T07:47:49 IST" duration-ms="4965" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="selectProduct()[pri:0, instance:TestScripts.ProductSelect@4470fbd6]" started-at="2024-03-25T07:47:49 IST" name="selectProduct" finished-at="2024-03-25T07:47:56 IST" duration-ms="7085" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectProduct -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:TestScripts.ProductSelect@4470fbd6]" started-at="2024-03-25T07:47:56 IST" name="closeDriver" finished-at="2024-03-25T07:48:00 IST" duration-ms="3110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- TestScripts.ProductSelect -->
      <class name="TestScripts.ProductOrderAndCheckOut">
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:11 IST" name="login" finished-at="2024-03-25T07:47:17 IST" duration-ms="5582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="testProductisPresentInCart(java.util.HashMap)[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:17 IST" name="testProductisPresentInCart" data-provider="provideData" finished-at="2024-03-25T07:47:24 IST" duration-ms="7394" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{date=24, country=ind, cvv=456, month=12, cardname=vijay}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestScripts.ProductOrderAndCheckOut.testProductisPresentInCart(ProductOrderAndCheckOut.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductisPresentInCart -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:24 IST" name="closeDriver" finished-at="2024-03-25T07:47:27 IST" duration-ms="3165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method is-config="true" signature="login()[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:27 IST" name="login" finished-at="2024-03-25T07:47:32 IST" duration-ms="4946" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="testProductisPresentInCart(java.util.HashMap)[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:32 IST" name="testProductisPresentInCart" data-provider="provideData" finished-at="2024-03-25T07:47:41 IST" duration-ms="8617" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{date=31, country=ind, cvv=789, month=09, cardname=hari}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestScripts.ProductOrderAndCheckOut.testProductisPresentInCart(ProductOrderAndCheckOut.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductisPresentInCart -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:TestScripts.ProductOrderAndCheckOut@1f9e9475]" started-at="2024-03-25T07:47:41 IST" name="closeDriver" finished-at="2024-03-25T07:47:44 IST" duration-ms="3125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- TestScripts.ProductOrderAndCheckOut -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
